const coreKeywords = [
  'SELLDROX',
  'Selldrox',
  'stexra',
  'stexra com',
  'stexra in',
  'ytsatex',
  'Dev Rajpurohit',
  'Dev Rajpurohit digital products',
  'AI automation',
  'ai auromation',
  'digital product',
  'digital products',
  'USA leads',
  'usa leads',
  'business leads',
  'lead generation',
  'business templates',
  'source code',
  'creative assets',
  'online courses',
  'digital resources',
  'marketing tools',
  'automation tools',
];

const topics = [
  'digital products',
  'digital product bundle',
  'AI automation',
  'automation tools',
  'USA leads',
  'business leads',
  'lead generation',
  'B2B leads',
  'startup resources',
  'business templates',
  'marketing templates',
  'source code',
  'website templates',
  'creative assets',
  'online courses',
  'growth tools',
  'sales resources',
  'agency resources',
  'SaaS resources',
  'entrepreneur tools',
  'small business tools',
  'digital vault',
  'premium resources',
  'downloadable products',
  'business automation',
  'workflow automation',
  'AI tools',
  'CRM templates',
  'email marketing leads',
  'social media templates',
  'notion templates',
  'excel templates',
  'google sheets templates',
  'landing page templates',
  'lead database',
  'sales leads',
  'marketing leads',
  'real estate leads',
  'ecommerce resources',
  'freelancer resources',
];

const modifiers = [
  'best',
  'premium',
  'affordable',
  'verified',
  'download',
  'instant download',
  'high quality',
  'professional',
  'ready to use',
  'for startups',
  'for agencies',
  'for entrepreneurs',
  'for creators',
  'for small business',
  'for marketers',
  'for sales teams',
  'for freelancers',
  'for ecommerce',
  'for USA business',
  'online',
  '2026',
  'India',
  'USA',
  'global',
  'bundle',
  'resources',
  'tools',
  'templates',
  'course',
  'software',
  'growth',
  'automation',
];

const brands = [
  'stexra',
  'stexra com',
  'stexra in',
  'Dev Rajpurohit',
  'Dev Rajpurohit stexra',
  'stexra by Dev Rajpurohit',
  'SELLDROX',
  'Selldrox',
  'ytsatex',
];

const focusBrands = [
  'stexra',
  'stexra com',
  'stexra in',
  'stexra digital products',
  'stexra AI automation',
  'stexra USA leads',
  'Dev Rajpurohit',
  'Dev Rajpurohit digital products',
  'Dev Rajpurohit AI automation',
  'Dev Rajpurohit USA leads',
  'Dev Rajpurohit stexra',
  'stexra by Dev Rajpurohit',
  'Dev Rajpurohit official',
  'Dev Rajpurohit business tools',
];

const locations = [
  'USA',
  'United States',
  'California',
  'Texas',
  'Florida',
  'New York',
  'Illinois',
  'Pennsylvania',
  'Ohio',
  'Georgia',
  'North Carolina',
  'Michigan',
  'New Jersey',
  'Virginia',
  'Washington',
  'Arizona',
  'Massachusetts',
  'Tennessee',
  'Indiana',
  'Missouri',
  'Maryland',
  'Wisconsin',
  'Colorado',
  'Minnesota',
  'South Carolina',
  'Alabama',
  'Louisiana',
  'Kentucky',
  'Oregon',
  'Oklahoma',
  'Connecticut',
  'Utah',
  'Iowa',
  'Nevada',
  'Arkansas',
  'Mississippi',
  'Kansas',
  'New Mexico',
  'Nebraska',
  'Idaho',
  'West Virginia',
  'Hawaii',
  'New Hampshire',
  'Maine',
  'Montana',
  'Rhode Island',
  'Delaware',
  'South Dakota',
  'North Dakota',
  'Alaska',
  'Vermont',
  'Wyoming',
  'Los Angeles',
  'New York City',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'Austin',
  'Jacksonville',
  'San Jose',
  'Fort Worth',
  'Columbus',
  'Charlotte',
  'San Francisco',
  'Indianapolis',
  'Seattle',
  'Denver',
  'Washington DC',
  'Boston',
  'El Paso',
  'Nashville',
  'Detroit',
  'Portland',
  'Las Vegas',
  'Miami',
];

const niches = [
  'real estate',
  'insurance',
  'finance',
  'healthcare',
  'dental',
  'fitness',
  'education',
  'coaching',
  'consulting',
  'restaurants',
  'local business',
  'ecommerce',
  'SaaS',
  'IT services',
  'digital marketing',
  'web design',
  'solar',
  'roofing',
  'home services',
  'law firms',
  'accounting',
  'travel',
  'beauty',
  'automotive',
  'construction',
  'retail',
  'B2B',
  'B2C',
];

function unique(values: string[]) {
  return Array.from(new Set(values.map((value) => value.trim()).filter(Boolean)));
}

export const seoKeywords = unique([
  ...coreKeywords,
  ...brands.flatMap((brand) => topics.map((topic) => `${brand} ${topic}`)),
  ...focusBrands.flatMap((brand) => modifiers.map((modifier) => `${modifier} ${brand}`)),
  ...focusBrands.flatMap((brand) => topics.map((topic) => `${brand} ${topic}`)),
  ...focusBrands.flatMap((brand) => locations.map((location) => `${brand} ${location}`)),
  ...focusBrands.flatMap((brand) => niches.map((niche) => `${brand} ${niche}`)),
  ...focusBrands.flatMap((brand) => niches.slice(0, 18).map((niche) => `${brand} ${niche} leads`)),
  ...topics.flatMap((topic) => modifiers.map((modifier) => `${modifier} ${topic}`)),
  ...locations.flatMap((location) => [
    `${location} leads`,
    `${location} business leads`,
    `${location} USA leads`,
    `${location} lead generation`,
    `${location} digital products`,
    `${location} AI automation`,
    `${location} marketing tools`,
    `${location} business templates`,
  ]),
  ...niches.flatMap((niche) => [
    `${niche} leads`,
    `${niche} USA leads`,
    `${niche} business leads`,
    `${niche} lead generation`,
    `${niche} automation`,
    `${niche} AI automation`,
    `${niche} marketing templates`,
    `${niche} digital products`,
    `${niche} business resources`,
    `${niche} sales tools`,
  ]),
  ...niches.flatMap((niche) => locations.slice(0, 20).map((location) => `${niche} leads in ${location}`)),
]);
